language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
before_script:
  - npm install -g bower
  - npm install -g gulp
  - npm install phantomjs
  - npm install -g karma
  - bower install
script: gulp